# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/list_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 198)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("* { background-color:rgb(41, 53, 59);  color: white;}\n"
"QPushButton {\n"
"border: 0px solid rgb(30, 39, 43);\n"
" border-right-width: 2px;\n"
"border-bottom-width: 2px;\n"
"border-top: 1px solid rgb(34, 44, 49);\n"
"border-left: 1px solid rgb(34, 44, 49);\n"
"}\n"
"QPushButton:hover {\n"
"border: 0px solid rgb(30, 39, 43);\n"
" border-right-width: 3px;\n"
"border-bottom-width: 3px;\n"
"border-top: 2px solid rgb(34, 44, 49);\n"
"border-left: 2px solid rgb(34, 44, 49);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(34, 44, 49);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.enable_start_date = QtWidgets.QCheckBox(Form)
        self.enable_start_date.setText("")
        self.enable_start_date.setObjectName("enable_start_date")
        self.gridLayout.addWidget(self.enable_start_date, 2, 0, 1, 1)
        self.enable_end_date = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enable_end_date.sizePolicy().hasHeightForWidth())
        self.enable_end_date.setSizePolicy(sizePolicy)
        self.enable_end_date.setText("")
        self.enable_end_date.setObjectName("enable_end_date")
        self.gridLayout.addWidget(self.enable_end_date, 3, 0, 1, 1)
        self.start_date = QtWidgets.QDateEdit(Form)
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.gridLayout.addWidget(self.start_date, 2, 2, 1, 1)
        self.end_date = QtWidgets.QDateEdit(Form)
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName("end_date")
        self.gridLayout.addWidget(self.end_date, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.color = QtWidgets.QToolButton(Form)
        self.color.setText("")
        self.color.setObjectName("color")
        self.gridLayout.addWidget(self.color, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save.sizePolicy().hasHeightForWidth())
        self.save.setSizePolicy(sizePolicy)
        self.save.setMinimumSize(QtCore.QSize(100, 40))
        self.save.setBaseSize(QtCore.QSize(0, 0))
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.delete_list = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_list.sizePolicy().hasHeightForWidth())
        self.delete_list.setSizePolicy(sizePolicy)
        self.delete_list.setMinimumSize(QtCore.QSize(100, 40))
        self.delete_list.setObjectName("delete_list")
        self.horizontalLayout.addWidget(self.delete_list)
        self.saveAsTxt = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAsTxt.sizePolicy().hasHeightForWidth())
        self.saveAsTxt.setSizePolicy(sizePolicy)
        self.saveAsTxt.setMinimumSize(QtCore.QSize(110, 40))
        self.saveAsTxt.setObjectName("saveAsTxt")
        self.horizontalLayout.addWidget(self.saveAsTxt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя:"))
        self.label_2.setText(_translate("Form", "Цвет:"))
        self.label_3.setText(_translate("Form", "Дата начала:"))
        self.label_4.setText(_translate("Form", "Дата ококнчания:"))
        self.save.setText(_translate("Form", "Сохранить"))
        self.delete_list.setText(_translate("Form", "Удалить"))
        self.saveAsTxt.setText(_translate("Form", "Сохранить в txt"))
