# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.scheduler import Scheduler
from os.path import realpath


def filename(name):
        return realpath(name)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 564)
        MainWindow.setStyleSheet("* { background-color:rgb(41, 53, 59);  color: white;}\n"
"QAbstractButton {\n"
"border: 0px solid rgb(30, 39, 43);\n"
" border-right-width: 2px;\n"
"border-bottom-width: 2px;\n"
"border-top: 1px solid rgb(34, 44, 49);\n"
"border-left: 1px solid rgb(34, 44, 49);\n"
"}\n"
"QAbstractButton:hover {\n"
"border: 0px solid rgb(30, 39, 43);\n"
" border-right-width: 3px;\n"
"border-bottom-width: 3px;\n"
"border-top: 2px solid rgb(34, 44, 49);\n"
"border-left: 2px solid rgb(34, 44, 49);\n"
"}\n"
"QAbstractButton:pressed {\n"
"background-color: rgb(34, 44, 49);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QCalendar{\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lists = QtWidgets.QListWidget(self.centralwidget)
        self.lists.setStyleSheet("QToolButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-width: 0px;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(59, 75, 85);\n"
"}\n"
"QListView::item:hover{\n"
"    background-color: rgb(59, 75, 85);\n"
"}\n"
"QListView::item:selected{\n"
"    background-color: rgb(50, 68, 85)\n"
"}")
        self.lists.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.lists.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.lists.setObjectName("lists")
        self.verticalLayout.addWidget(self.lists)
        self.list_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_add.sizePolicy().hasHeightForWidth())
        self.list_add.setSizePolicy(sizePolicy)
        self.list_add.setMinimumSize(QtCore.QSize(0, 50))
        self.list_add.setObjectName("list_add")
        self.verticalLayout.addWidget(self.list_add)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.calendar = Scheduler(self.centralwidget)
        self.calendar.setEnabled(True)
        tmp = QtGui.QTextCharFormat()
        tmp.setForeground(QtGui.QBrush(QtCore.Qt.white))
        tmp.setBackground(QtGui.QBrush(QtGui.QColor(34, 44, 49)))
        self.calendar.setHeaderTextFormat(tmp)
        self.calendar.hide()
        self.calendar.setStyleSheet("")
        self.calendar.setObjectName("calendar")
        self.verticalLayout_5.addWidget(self.calendar)
        self.tasks = QtWidgets.QListWidget(self.centralwidget)
        self.tasks.setStyleSheet("QListView::item:hover{\n"
"    background-color: rgb(59, 75, 85);\n"
"}\n"
"QListView::item:selected{\n"
"    background-color: rgb(50, 68, 85)\n"
"}")
        self.tasks.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tasks.setObjectName("tasks")
        self.verticalLayout_5.addWidget(self.tasks)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.task_add = QtWidgets.QToolButton(self.centralwidget)
        self.task_add.setMinimumSize(QtCore.QSize(40, 40))
        self.task_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(filename("ui/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_add.setIcon(icon)
        self.task_add.setArrowType(QtCore.Qt.NoArrow)
        self.task_add.setObjectName("task_add")
        self.verticalLayout_2.addWidget(self.task_add)
        self.set_sort = QtWidgets.QToolButton(self.centralwidget)
        self.set_sort.setMinimumSize(QtCore.QSize(40, 40))
        self.set_sort.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(filename("ui/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_sort.setIcon(icon1)
        self.set_sort.setObjectName("set_sort")
        self.verticalLayout_2.addWidget(self.set_sort)
        self.set_filtration = QtWidgets.QToolButton(self.centralwidget)
        self.set_filtration.setMinimumSize(QtCore.QSize(40, 40))
        self.set_filtration.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(filename("ui/filter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_filtration.setIcon(icon2)
        self.set_filtration.setObjectName("set_filtration")
        self.verticalLayout_2.addWidget(self.set_filtration)
        self.set_view = QtWidgets.QToolButton(self.centralwidget)
        self.set_view.setMinimumSize(QtCore.QSize(40, 40))
        self.set_view.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(filename("ui/calendar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_view.setIcon(icon3)
        self.set_view.setCheckable(False)
        self.set_view.setChecked(False)
        self.set_view.setObjectName("set_view")
        self.verticalLayout_2.addWidget(self.set_view)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(36, -1, 12, -1)
        self.verticalLayout_7.setSpacing(24)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("label")
        self.verticalLayout_7.addWidget(self.name)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.end_date = QtWidgets.QLabel(self.centralwidget)
        self.end_date.setText("")
        self.end_date.setObjectName("end_date")
        self.gridLayout_5.addWidget(self.end_date, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.tags = QtWidgets.QLabel(self.centralwidget)
        self.tags.setText("")
        self.tags.setObjectName("tags")
        self.gridLayout_5.addWidget(self.tags, 3, 1, 1, 1)
        self.start_date = QtWidgets.QLabel(self.centralwidget)
        self.start_date.setText("")
        self.start_date.setObjectName("start_date")
        self.gridLayout_5.addWidget(self.start_date, 1, 1, 1, 1)
        self.priority = QtWidgets.QLabel(self.centralwidget)
        self.priority.setText("")
        self.priority.setObjectName("priority")
        self.gridLayout_5.addWidget(self.priority, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 4, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.verticalLayout_7.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(3, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.list_add.setText(_translate("MainWindow", "Добавить список"))
        self.name.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "Приоритет:"))
        self.label_4.setText(_translate("MainWindow", "Дата начала:"))
        self.label_8.setText(_translate("MainWindow", "Теги:"))
        self.label_6.setText(_translate("MainWindow", "Дата окончания:"))
