# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 231)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("* {\n"
"     background-color: rgb(41, 53, 59);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 0px solid rgb(30, 39, 43);\n"
"    border-right-width: 2px;\n"
"    border-bottom-width: 2px;\n"
"    border-top: 1px solid rgb(34, 44, 49);\n"
"    border-left: 1px solid rgb(34, 44, 49);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 0px solid rgb(30, 39, 43);\n"
"    border-right-width: 3px;\n"
"    border-bottom-width: 3px;\n"
"    border-top: 2px solid rgb(34, 44, 49);\n"
"    border-left: 2px solid rgb(34, 44, 49);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(34, 44, 49);\n"
"}\n"
"\n"
"@keyframes activate {\n"
"from {;border-color:  rgba(0, 170, 255, 0)}\n"
"to {border-color: rgba(0, 170, 255, 1);}\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 0px solid rgb(62, 74, 80);\n"
"border-bottom-width: 2px;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 0px solid rgba(0, 170, 255, 0);\n"
"border-bottom-width: 2px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 2, 1, 1)
        self.Label = QtWidgets.QLabel(Form)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 0, 1, 1, 1)
        self.enable_end_date = QtWidgets.QCheckBox(Form)
        self.enable_end_date.setText("")
        self.enable_end_date.setObjectName("enable_end_date")
        self.gridLayout.addWidget(self.enable_end_date, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        self.tags = QtWidgets.QLineEdit(Form)
        self.tags.setReadOnly(False)
        self.tags.setObjectName("tags")
        self.gridLayout.addWidget(self.tags, 4, 2, 1, 1)
        self.priority = QtWidgets.QSpinBox(Form)
        self.priority.setObjectName("priority")
        self.priority.setMinimum(1)
        self.priority.setMaximum(4)
        self.gridLayout.addWidget(self.priority, 1, 2, 1, 1)
        self.Label_2 = QtWidgets.QLabel(Form)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 1, 1, 1, 1)
        self.enable_start_date = QtWidgets.QCheckBox(Form)
        self.enable_start_date.setText("")
        self.enable_start_date.setObjectName("enable_start_date")
        self.gridLayout.addWidget(self.enable_start_date, 2, 0, 1, 1)
        self.start_date = QtWidgets.QDateEdit(Form)
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.gridLayout.addWidget(self.start_date, 2, 2, 1, 1)
        self.Label_4 = QtWidgets.QLabel(Form)
        self.Label_4.setObjectName("Label_4")
        self.gridLayout.addWidget(self.Label_4, 3, 1, 1, 1)
        self.end_date = QtWidgets.QDateEdit(Form)
        self.end_date.setCalendarPopup(True)
        self.end_date.setObjectName("end_date")
        self.gridLayout.addWidget(self.end_date, 3, 2, 1, 1)
        self.Label_3 = QtWidgets.QLabel(Form)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout.addWidget(self.Label_3, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save.sizePolicy().hasHeightForWidth())
        self.save.setSizePolicy(sizePolicy)
        self.save.setMinimumSize(QtCore.QSize(100, 40))
        self.save.setBaseSize(QtCore.QSize(100, 0))
        self.save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.delete_task = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_task.sizePolicy().hasHeightForWidth())
        self.delete_task.setSizePolicy(sizePolicy)
        self.delete_task.setMinimumSize(QtCore.QSize(100, 40))
        self.delete_task.setObjectName("delete_task")
        self.horizontalLayout.addWidget(self.delete_task)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактировать задачу"))
        self.Label.setText(_translate("Form", "Имя:"))
        self.label.setText(_translate("Form", "Теги:"))
        self.Label_2.setText(_translate("Form", "Приоритет:"))
        self.Label_4.setText(_translate("Form", "Дата окончания:"))
        self.Label_3.setText(_translate("Form", "Дата начала:"))
        self.save.setText(_translate("Form", "Сохранить"))
        self.save.setShortcut(_translate("Form", "Return"))
        self.delete_task.setText(_translate("Form", "Удалить"))
